{% set name = "miss-hit" %}
{% set version = "0.9.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/miss_hit-{{ version }}.tar.gz
  sha256: 92be5478413714e89c1b6b96945867e220c1294c0ed52e9008421f48faa97f33

build:
  entry_points:
    - mh_lint = miss_hit.mh_lint:main
    - mh_diff = miss_hit.mh_diff:main
    - mh_copyright = miss_hit.mh_copyright:main
    - mh_trace = miss_hit.mh_trace:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - miss-hit-core
    - pip
  run:
    - python >=3.6,<4.0
    - miss-hit-core {{ version }}

test:
  imports:
    - miss_hit
  commands:
    - pip check
    - mh_lint --help
    - mh_diff --help
    - mh_copyright --help
    - mh_trace --help
  requires:
    - pip

about:
  home: https://misshit.org
  summary: Static analysis and other utilities for programs written in the MATLAB/Simulink and Octave languages.
  license: AGPL-3.0-only
  license_file: LICENSE.APGL

extra:
  recipe-maintainers:
    - ngam
